import type {
  BattleTunables,
  ChiMoveDefinition,
  ChiMoveId,
  HeroStats,
  MoveId,
  PhysicalMoveDefinition,
  PhysicalMoveId,
} from '../core/types';

export const heroBaseStats: HeroStats = {
  strength: 14,
  dexterity: 13,
  vitality: 12,
  focus: 14,
  defense: 8,
};

export const enemyBaseStats: HeroStats = {
  strength: 9,
  dexterity: 7,
  vitality: 28,
  focus: 4,
  defense: 5,
};

export const bossEnemyStats: HeroStats = {
  strength: 15,
  dexterity: 9,
  vitality: 46,
  focus: 8,
  defense: 11,
};

export const playerPhysicalMoves: Record<PhysicalMoveId, PhysicalMoveDefinition> = {
  ironPalm: {
    id: 'ironPalm',
    name: 'Iron Palm Rush',
    animation: 'attack',
    strengthScale: 4.2,
    dexterityScale: 1.35,
    flatBonus: 0,
    chiGain: 8,
    stopDistance: 1.92,
    impactDelayMs: 460,
    recoveryMs: 460,
    timeScale: 1.18,
  },
  dragonHeel: {
    id: 'dragonHeel',
    name: 'Dragon Heel Kick',
    animation: 'kick',
    strengthScale: 3.15,
    dexterityScale: 2.55,
    flatBonus: 10,
    chiGain: 10,
    stopDistance: 2.18,
    impactDelayMs: 540,
    recoveryMs: 430,
    timeScale: 1.05,
  },
  tigerHook: {
    id: 'tigerHook',
    name: 'Tiger Hook',
    animation: 'hook',
    strengthScale: 3.7,
    dexterityScale: 2.05,
    flatBonus: 6,
    chiGain: 9,
    stopDistance: 1.86,
    impactDelayMs: 390,
    recoveryMs: 360,
    timeScale: 1.2,
  },
  risingUppercut: {
    id: 'risingUppercut',
    name: 'Rising Uppercut',
    animation: 'uppercut',
    strengthScale: 4.75,
    dexterityScale: 1.15,
    flatBonus: 8,
    chiGain: 8,
    stopDistance: 1.9,
    impactDelayMs: 430,
    recoveryMs: 410,
    timeScale: 1.12,
  },
  craneHighKick: {
    id: 'craneHighKick',
    name: 'Crane High Kick',
    animation: 'highKick',
    strengthScale: 2.9,
    dexterityScale: 3.2,
    flatBonus: 12,
    chiGain: 11,
    stopDistance: 2.22,
    impactDelayMs: 520,
    recoveryMs: 430,
    timeScale: 1.05,
  },
  sweepKick: {
    id: 'sweepKick',
    name: 'Lotus Sweep',
    animation: 'sweepKick',
    strengthScale: 2.65,
    dexterityScale: 2.85,
    flatBonus: 7,
    chiGain: 12,
    stopDistance: 2.05,
    impactDelayMs: 500,
    recoveryMs: 390,
    timeScale: 1.08,
  },
  lungeSpinKick: {
    id: 'lungeSpinKick',
    name: 'Tempest Spin Kick',
    animation: 'lungeSpinKick',
    strengthScale: 3.2,
    dexterityScale: 3.45,
    flatBonus: 14,
    chiGain: 13,
    stopDistance: 2.2,
    impactDelayMs: 560,
    recoveryMs: 440,
    timeScale: 1.05,
  },
};

export const playerChiMoves: Record<ChiMoveId, ChiMoveDefinition> = {
  chiBreaker: {
    id: 'chiBreaker',
    name: 'Chi Breaker',
    kind: 'damage',
    chiCost: 30,
    focusScale: 7.5,
    strengthScale: 2.1,
    flatBonus: 32,
    chargeMs: 1500,
    flashMs: 340,
    timeScale: 0.58,
  },
  healingChi: {
    id: 'healingChi',
    name: 'Healing Chi',
    kind: 'heal',
    chiCost: 24,
    focusScale: 5.9,
    strengthScale: 0.85,
    flatBonus: 34,
    chargeMs: 880,
    flashMs: 180,
    timeScale: 0.84,
  },
};

export const defaultEquippedMoves: MoveId[] = ['ironPalm', 'dragonHeel', 'chiBreaker'];

export const moveDebugOptions: Array<{ id: MoveId; name: string }> = [
  { id: 'ironPalm', name: 'Iron Palm Rush' },
  { id: 'dragonHeel', name: 'Dragon Heel Kick' },
  { id: 'tigerHook', name: 'Tiger Hook' },
  { id: 'risingUppercut', name: 'Rising Uppercut' },
  { id: 'craneHighKick', name: 'Crane High Kick' },
  { id: 'sweepKick', name: 'Lotus Sweep' },
  { id: 'lungeSpinKick', name: 'Tempest Spin Kick' },
  { id: 'chiBreaker', name: 'Chi Breaker' },
  { id: 'healingChi', name: 'Healing Chi' },
];

export const battleTunables: BattleTunables = {
  atbMax: 100,
  playerAtbMultiplier: 5.2,
  enemyAtbMultiplier: 3.4,
  attackDefenseScale: 1.55,
  chiMultiplier: 7.5,
  chiFlatBonus: 32,
  chiCost: 30,
  approachDurationMs: 540,
  returnDurationMs: 520,
  enemyActionDurationMs: 600,
  chiChargeMs: 1450,
  chiFlashMs: 260,
  victoryHoldMs: 6500,
};
